[session]
start = "0915"
end = "1530"

[reload]
interval_minutes = 3
buffer_seconds = -12

[sync]
remote_sync = false

[merge]
filter_ltp = "400-6000"
sort_keys = ["volume_fast", "vol_surge"]
last_ndays = 14  # 0 means None/Disabled

[server]
host = "localhost"
port = 5000
log_level = "info"