//@version=4
//study(title="Squeeze Pro Scanner", shorttitle="SQZPRO_SCANNER", overlay=true)

strategy(title="Squeeze Pro Scanner", shorttitle="SQZPRO_SCANNER", overlay=true, calc_on_every_tick=true)


//----------- Symbols List ------------------


//---Only Commodities----

// symb1 = "USDINR"
// symb2 = "CL1!"
// symb3 = "NG1!"
// symb4 = "HG1!"
// symb5 = "GC1!"
// symb6 = "CRUDEOIL1!"
// symb7 = "NATURALGAS1!"
// symb8 = "COPPER1!"
// symb9 ="ALUMINIUM1!"
// symb10 = "ZINC1!"

// tf1 = "15"
// tf2 = "30"
// tf3 = "60"
// tf4 = '120'
// tfcount = 4


//----- Top 15 Equities and Top 5 Comm Combined

// symb1 = "BANKNIFTY"
// symb2 = "NIFTY"
// symb3 = "RELIANCE"
// symb4 = "INFY"
// symb5 = "TECHM"
// symb6="TATASTEEL"
// symb7 = "GODREJCP"
// symb8 = "ICICIBANK"
// symb9 = "AXISBANK"
// symb10= "SBIN"
// symb11 = "CADILAHC"
// symb12 = "JINDALSTEL"
// symb13 = "TATAMOTORS"
// symb14 = "BPCL"
// symb15 = "HINDPETRO"
// symb16 = "CRUDEOIL1!"
// symb17= "NATURALGAS1!"
// symb18 = "COPPER1!"
// symb19 ="ALUMINIUM1!"
// symb20 = "ZINC1!"


// tf1 = "30"
// tf2 = '60'
// tf3 = ""
// tf4 = ""
// tfcount = 2


//----- Top 2 Equities and Top 7 Comm Combined

// symb1 = "USDCAD"
// symb2 = "CL1!"
// symb3 = "NG1!"
// symb4 = "HG1!"
// symb5 = "CRUDEOIL1!"
// symb6 = "NATURALGAS1!"
// symb7 = "COPPER1!"
// symb8 = "BANKNIFTY"
// symb9 = "NIFTY"


// tf1 = "5"
// tf2 = '30'
// tf3 = "60"
// tf4 = ""
// tfcount = 3



//----- Top 10 Eq and 3 Comm, 3 TFs

symb1 = "CRUDEOIL1!"
symb2= "NATURALGAS1!"
symb3="COPPER1!"
symb4 = "BANKNIFTY"
symb5 = "NIFTY"
symb6 = "RELIANCE"
symb7 = "INFY"
symb8 = "TECHM"
symb9="TATASTEEL"
symb10 = "AXISBANK"
symb11= "SBIN"
symb12 = "CADILAHC"
symb13 = "TATAMOTORS"


tf1 = "5"
tf2 = '15'
tf3 = "30"
tf4 = ""
tfcount = 3



//---Top 7 Commodities----

// symb1 = "USDCAD"
// symb2 = "CL1!"
// symb3 = "NG1!"
// symb4 = "HG1!"
// symb5 = "CRUDEOIL1!"
// symb6 = "NATURALGAS1!"
// symb7 = "COPPER1!"


// tf1 = "5"
// tf2 = "15"
// tf3 = "30"
// tf4 = ""
// tfcount = 3

//----Constants-------


show_fire_alert = true
show_adx_alert = false
show_erg_alert = false
show_summ_alert = true


show_sqz = true



show_comm = true
show_eq = true


// if na(time(timeframe.period, "1000-1505"))
//     show_eq := false

// OSc Code Consts

UP = 1
DOWN = 2
NEUTRAL = 0

YELLOW=1
RED=2
ORANGE=3
NOSQZ=0

rad2degree=180/3.14159265359
lookback_period = 1
smoothing = 3


//Sqz Code variables
source = close

calc_sqz()=>
    length = 20
    ma = sma(source, length)
    devBB = stdev(source, length)
    devKC = sma(tr, length)
    
    
    //Bollinger 2x
    upBB = ma + devBB * 2
    lowBB = ma - devBB * 2
    
    //Keltner 2x
    upKCWide = ma + devKC * 2
    lowKCWide = ma - devKC * 2
    
    //Keltner 1.5x
    upKCNormal = ma + devKC * 1.5
    lowKCNormal = ma - devKC * 1.5
    
    //Keltner 1x
    upKCNarrow = ma + devKC
    lowKCNarrow = ma - devKC
    
    sqzOnWide = lowBB >= lowKCWide and upBB <= upKCWide  //WIDE SQUEEZE: ORANGE
    sqzOnNormal = lowBB >= lowKCNormal and upBB <= upKCNormal  //NORMAL SQUEEZE: RED
    sqzOnNarrow = lowBB >= lowKCNarrow and upBB <= upKCNarrow  //NARROW SQUEEZE: YELLOW
    sqzOffWide = lowBB < lowKCWide and upBB > upKCWide  //FIRED WIDE SQUEEZE
    sqzOffNormal = lowBB < lowKCNormal and upBB > upKCNormal  //FIRED NORMAL SQUEEZE
    sqzOffNarrow = lowBB < lowKCNarrow and upBB > upKCNarrow  //FIRED NARROW SQUEEZE
    noSqz = sqzOnWide == false and sqzOffWide == false  //NO SQUEEZE
    
    fire_code = sqzOffNarrow and sqzOnNarrow[1] ? YELLOW :
       sqzOffNormal and sqzOnNormal[1] ? RED :
       sqzOffWide and sqzOnWide[1] ? ORANGE : NOSQZ
    
    
    sqzcolornum = noSqz ? NOSQZ : sqzOnNarrow ? YELLOW : 
     sqzOnNormal ? RED : sqzOnWide ? ORANGE : NOSQZ

    
    [sqzcolornum,fire_code]
        

//------ End of Sqz Code--------

decodeSqzColorCode(st) => 
    col= st == YELLOW ? color.yellow : st == RED ? color.red : st == ORANGE ? color.orange : color.gray
    txt = st == YELLOW ? 'Yellow' : st == RED ? 'Red' : st == ORANGE ? 'Orange' : 'Nosqz'
    [txt, col]

decodeMovementCode(st) => 
    col = st == UP ? color.aqua : st == DOWN ? color.red : color.gray
    txt = st == UP ? 'Up' : st == DOWN ? 'Down' : 'Neutral'
    [txt, col]


angle(_src,osc_avg_tr) =>
    ang=rad2degree*atan((_src-nz(_src[lookback_period]))/(lookback_period*osc_avg_tr))
    
get_osc_movement_with_params(osc, osc_ft, osc_cut_off,osc_avg_atr,osc_MAX,osc_MIN) =>
    osc_fb = -osc_ft
    osc_slope = linreg(angle(osc,osc_avg_atr), smoothing, 0)
    trend = osc_slope > osc_ft or osc >= (osc_MAX - osc_cut_off) ? UP: osc_slope < osc_fb or osc <= (osc_MIN + osc_cut_off) ? DOWN : NEUTRAL
    trend


// ADX Code

STRAT_NEUTRAL = 0
STRAT_LONG = 1 
STRAT_SHORT = 2  
STRAT_ENTER_LONG =3
STRAT_ENTER_SHORT = 4 
STRAT_EXIT_LONG  =5
STRAT_EXIT_SHORT  = 6


decodeStratCode(adx_code)=>
    adx_col = adx_code == STRAT_EXIT_LONG ? color.new(color.yellow,transp= 0) : adx_code == STRAT_EXIT_SHORT ? color.new(color.blue,transp= 0) :  
       adx_code == STRAT_ENTER_LONG ? color.new(color.lime,transp= 0) : adx_code == STRAT_ENTER_SHORT ? color.new(color.red,transp=0) :  
       adx_code == STRAT_LONG ? color.new(color.aqua,transp= 60) : adx_code == STRAT_SHORT ? color.new(color.orange,transp= 60) : color.new(color.gray,transp= 60)
     
    
    adx_txt = adx_code == STRAT_EXIT_LONG ? 'ExUp' : adx_code == STRAT_EXIT_SHORT ? 'ExDn' :  
       adx_code == STRAT_ENTER_LONG ? 'EnUp' : adx_code == STRAT_ENTER_SHORT ? 'EnDn' :  
       adx_code == STRAT_LONG ? 'Up' : adx_code == STRAT_SHORT ? 'Dn' : 'Na'
     
    [adx_txt,adx_col]


RANGE_BACK_BARS = 100


calc_ADX() =>
    adx_len = 14
    adx_lensig = 14
    
    // Get ADX, PDI and MDI values
    [plus, minus, adx] = dmi(adx_len, adx_lensig)
    
    adx_MAX=highest(adx,RANGE_BACK_BARS)
    adx_MIN=lowest(adx,RANGE_BACK_BARS)
    
    
    adx_avg_tr =  adx_MAX - adx_MIN
    adx_cut_off= 0
    
    adx_filter_range = 2.55
    
    adx_ft = adx_filter_range
    adx_fb = -adx_filter_range
    
    
    adxentrylevel = 49
    adxlowerlevel = 9
    
    
    adx_trend = get_osc_movement_with_params(adx,adx_ft,adx_cut_off, adx_avg_tr,adx_MAX,adx_MIN)
    
    diPositive = plus > minus
    diNegative = not diPositive
    
    adxinside = (diPositive and adx >= minus and adx <= plus) or (diNegative and adx >= plus and adx <= minus)
    
    adxvalidtrend = adx_trend == UP or adx_trend == NEUTRAL 
    
    adxvalidtrendentry = (adx >= adxlowerlevel and adx <= adxentrylevel) or adxinside
     
    buyCond = diPositive and adxvalidtrend
    sellCond = diNegative and adxvalidtrend
    
    
    adxJustCrossed = cross(adx, plus) or cross(adx, minus)
    
    adxjustout = (adxinside[1] and not adxinside)
    adxjustin = (not adxinside[1] and adxinside)
    
    di_crossover = (diNegative[1] and diPositive) or (diNegative and diPositive[1]) 
    
    
    validlongentry = buyCond and adxvalidtrendentry
    validshortentry = sellCond and adxvalidtrendentry
    
    noTradeZone = not adxvalidtrend or di_crossover
    
    
    // get_active_position() =>
    active_position = false
    active_position := ((validlongentry or validshortentry) and not active_position[1] ? true : noTradeZone ? false : active_position[1])
    active_position

    //active_position = get_active_position()
    
    enterLong = validlongentry  and not active_position[1]
    enterShort =  validshortentry and not active_position[1]
    
    
    longpos = buyCond  and  active_position
    shortpos = sellCond and active_position
    
    
    exitLong = noTradeZone and longpos[1]
    exitShort = noTradeZone and shortpos[1]
    
    adx_status_code = exitLong ? STRAT_EXIT_LONG : exitShort ? STRAT_EXIT_SHORT :  
     enterLong ? STRAT_ENTER_LONG : enterShort ? STRAT_ENTER_SHORT :  
     longpos ? STRAT_LONG : shortpos ? STRAT_SHORT : STRAT_NEUTRAL
     
    adx_status_code



//----- SMI Ergo

calc_SMI_Erg()=>
    erg_longlen =14
    erg_shortlen = 8
    erg_siglen = 14
    erg_smoothing = 3
    
    erg1 = tsi(source, erg_shortlen, erg_longlen)
    
    erg = ema(erg1,erg_smoothing)
    
    sig = ema(erg1, erg_siglen)
    
    
    erg_MAX=highest(erg,RANGE_BACK_BARS)
    erg_MIN=lowest(erg,RANGE_BACK_BARS)
    
    erg_MID = (erg_MAX + erg_MIN)/2
    
    erg_avg_tr =  erg_MAX - erg_MIN
    erg_cut_off= 0
    
    erg_filter_range = 2
    
    erg_ft = erg_filter_range
    erg_fb = -erg_filter_range
    
    erg_trend = get_osc_movement_with_params(erg,erg_ft,erg_cut_off, erg_avg_tr,erg_MAX,erg_MIN)

    erg_validlong =  erg_trend == UP
    erg_validshort = erg_trend == DOWN
    
    erg_diPositive = erg > sig
    erg_diNegative = not erg_diPositive
    
    
    erg_di_crossover = (erg_diNegative[1] and erg_diPositive) or (erg_diNegative and erg_diPositive[1]) 
    
    
    erg_buyCond = erg_diPositive and erg_trend != DOWN
    erg_sellCond = erg_diNegative and erg_trend != UP
    
    
    ergvalidtrend = erg_buyCond or erg_sellCond
    
    erg_validlongentry = erg_buyCond and erg_validlong 
    erg_validshortentry = erg_sellCond and erg_validshort
    
    erg_noTradeZone = not ergvalidtrend or erg_di_crossover 
    
    
    erg_active_position = false
    erg_active_position := ((erg_validlongentry or erg_validshortentry) and not erg_active_position[1] ? true : erg_noTradeZone ? false : erg_active_position[1])
    
    
    erg_enterLong = erg_validlongentry  and not erg_active_position[1] 
    erg_enterShort =  erg_validshortentry and not erg_active_position[1]
    
    
    erg_longpos = erg_buyCond  and  erg_active_position
    erg_shortpos = erg_sellCond and erg_active_position
    
    
    erg_exitLong = erg_noTradeZone and erg_longpos[1] 
    erg_exitShort = erg_noTradeZone and erg_shortpos[1]
    
    
    erg_status_code = erg_exitLong ? STRAT_EXIT_LONG : erg_exitShort ? STRAT_EXIT_SHORT :  
     erg_enterLong ? STRAT_ENTER_LONG : erg_enterShort ? STRAT_ENTER_SHORT :  
     erg_longpos ? STRAT_LONG : erg_shortpos ? STRAT_SHORT : STRAT_NEUTRAL
     
    
    erg_status_code


//--------------- Trend Code

sep = " : "
screener_sep = "----------------\n"


check_if_comm_list(symb) => symb == symb1 or symb == symb2 or symb == symb3 
//or symb == symb4 or symb == symb5 or symb == symb6 or symb == symb7

check_if_eq_list(symb) => not check_if_comm_list(symb)



get_trend_num(trend_code) =>
    trend_code == UP ? 1 : trend_code == DOWN ? -1 : 0



get_status_code_trend_num(st) =>
    st == STRAT_ENTER_LONG or st == STRAT_LONG or st == STRAT_EXIT_SHORT ? 1 : st == STRAT_ENTER_SHORT or st == STRAT_SHORT or st == STRAT_EXIT_LONG ? -1 : 0


get_summary_trend_code(adx_code,erg_code) =>
    st_num = get_status_code_trend_num(adx_code) + 
      get_status_code_trend_num(erg_code)
     
    
    summ_trend_code = st_num >= 1 ? STRAT_LONG : st_num <= -1 ? STRAT_SHORT : STRAT_NEUTRAL
    
    any_long_entry =  adx_code == STRAT_ENTER_LONG or erg_code == STRAT_ENTER_LONG
    
    any_short_entry = adx_code == STRAT_ENTER_SHORT or erg_code == STRAT_ENTER_SHORT

    summ_trend_code := (summ_trend_code == STRAT_LONG and any_long_entry and st_num == 2)? STRAT_ENTER_LONG :   
      (summ_trend_code == STRAT_SHORT and any_short_entry and st_num == -2) ? STRAT_ENTER_SHORT :  summ_trend_code
    
    summ_trend_code


calc_final_summary(adx_code,erg_code) =>

    summ_trend_code = get_summary_trend_code(adx_code,erg_code)
    [summ_txt, summ_col] = decodeStratCode(summ_trend_code)
            
    
    summ_entry = summ_trend_code == STRAT_ENTER_LONG or summ_trend_code == STRAT_ENTER_SHORT
    
    curr_active_pos = false
    curr_active_pos := curr_active_pos[1]
    
    
    buyCond = summ_trend_code == STRAT_ENTER_LONG or summ_trend_code == STRAT_LONG
    sellCond = summ_trend_code == STRAT_ENTER_SHORT or summ_trend_code == STRAT_SHORT
    
    
    validtrend = buyCond or sellCond
    
    validlongentry = summ_trend_code == STRAT_ENTER_LONG 
    validshortentry = summ_trend_code == STRAT_ENTER_SHORT 
    
    
    enterLong = validlongentry  and not curr_active_pos
    enterShort =  validshortentry and not curr_active_pos
    
    
    curr_active_pos := (enterLong or enterShort) ? true :  curr_active_pos
    
    
    longpos = buyCond  and  curr_active_pos 
    shortpos = sellCond and  curr_active_pos
    
    di_change = (longpos[1] and not buyCond) or (shortpos[1] and not sellCond) 
    noTrade =  di_change or not validtrend 
    
    exitLong = noTrade and longpos[1] and curr_active_pos[1]
    exitShort = noTrade and shortpos[1] and curr_active_pos[1]
    
    
    curr_active_pos := (exitLong or exitShort) ? false : curr_active_pos
    
    final_summary_status_code = exitLong ? STRAT_EXIT_LONG : exitShort ? STRAT_EXIT_SHORT :  
         enterLong ? STRAT_ENTER_LONG : enterShort ? STRAT_ENTER_SHORT :  
         longpos ? STRAT_LONG : shortpos ? STRAT_SHORT : STRAT_NEUTRAL
    
    
    final_summary_status_code


get_all_status_codes() =>

    [sqzcolornum,fire_code] = calc_sqz()
    
    adx_status_code = calc_ADX()
    
    erg_status_code = calc_SMI_Erg()
    
    final_summary_status_code = calc_final_summary(adx_status_code,erg_status_code)

    [sqzcolornum, fire_code, adx_status_code,erg_status_code,final_summary_status_code]



symb_arr = array.new_string(0)
tf_arr = array.new_string(0)
sqcolor_arr = array.new_int(0)
adx_status_arr = array.new_int(0)
erg_status_arr = array.new_int(0)
summ_status_arr = array.new_int(0)

fire_sqz_arr = array.new_int(0)



screenerFunc() => get_all_status_codes()

updateStatusArr(symb,tf, sqcolor_code, fire_code,adx_code,erg_code,final_summary_status_code) =>
    ignore = false
    if (not show_comm and check_if_comm_list(symb) or (not show_eq and check_if_eq_list(symb)))
        ignore := true
    
    if not ignore
        array.push(symb_arr, symb)
        array.push(tf_arr, tf)
        array.push(sqcolor_arr,sqcolor_code)
        array.push(fire_sqz_arr,fire_code)
        array.push(adx_status_arr,adx_code)
        array.push(erg_status_arr,erg_code)
        array.push(summ_status_arr,final_summary_status_code)

        
f_sec(symb, tf) =>
    [sqzcol_code,fire_code,adx_code,erg_code,final_summary_status_code] = 
      security(symb, tf, screenerFunc(), lookahead = barmerge.lookahead_on)
      
    updateStatusArr(symb,tf,sqzcol_code,fire_code,adx_code,erg_code,final_summary_status_code)


// Top 10 Symbols  4 TFs

// f_sec(symb1, tf1)
// f_sec(symb1, tf2)
// f_sec(symb1, tf3)
// f_sec(symb1, tf4)

// f_sec(symb2, tf1)
// f_sec(symb2, tf2)
// f_sec(symb2, tf3)
// f_sec(symb2, tf4)

// f_sec(symb3, tf1)
// f_sec(symb3, tf2)
// f_sec(symb3, tf3)
// f_sec(symb3, tf4)

// f_sec(symb4, tf1)
// f_sec(symb4, tf2)
// f_sec(symb4, tf3)
// f_sec(symb4, tf4)

// f_sec(symb5, tf1)
// f_sec(symb5, tf2)
// f_sec(symb5, tf3)
// f_sec(symb5, tf4)

// f_sec(symb6, tf1)
// f_sec(symb6, tf2)
// f_sec(symb6, tf3)
// f_sec(symb6, tf4)

// f_sec(symb7, tf1)
// f_sec(symb7, tf2)
// f_sec(symb7, tf3)
// f_sec(symb7, tf4)

// f_sec(symb8, tf1)
// f_sec(symb8, tf2)
// f_sec(symb8, tf3)
// f_sec(symb8, tf4)

// f_sec(symb9, tf1)
// f_sec(symb9, tf2)
// f_sec(symb9, tf3)
// f_sec(symb9, tf4)

// f_sec(symb10, tf1)
// f_sec(symb10, tf2)
// f_sec(symb10, tf3)
// f_sec(symb10, tf4)


//Top 20 Symbols, 2 TFs

// f_sec(symb1, tf1)
// f_sec(symb1, tf2)

// f_sec(symb2, tf1)
// f_sec(symb2, tf2)

// f_sec(symb3, tf1)
// f_sec(symb3, tf2)

// f_sec(symb4, tf1)
// f_sec(symb4, tf2)

// f_sec(symb5, tf1)
// f_sec(symb5, tf2)

// f_sec(symb6, tf1)
// f_sec(symb6, tf2)

// f_sec(symb7, tf1)
// f_sec(symb7, tf2)

// f_sec(symb8, tf1)
// f_sec(symb8, tf2)


// f_sec(symb9, tf1)
// f_sec(symb9, tf2)

// f_sec(symb10, tf1)
// f_sec(symb10, tf2)

// f_sec(symb11, tf1)
// f_sec(symb11, tf2)

// f_sec(symb12, tf1)
// f_sec(symb12, tf2)

// f_sec(symb13, tf1)
// f_sec(symb13, tf2)

// f_sec(symb14, tf1)
// f_sec(symb14, tf2)

// f_sec(symb15, tf1)
// f_sec(symb15, tf2)

// f_sec(symb16, tf1)
// f_sec(symb16, tf2)

// f_sec(symb17, tf1)
// f_sec(symb17, tf2)

// f_sec(symb18, tf1)
// f_sec(symb18, tf2)

// f_sec(symb19, tf1)
// f_sec(symb19, tf2)

// f_sec(symb20, tf1)
// f_sec(symb20, tf2)

//---- Top 13 Symbs 3 TFs

f_sec(symb1, tf1)
f_sec(symb1, tf2)
f_sec(symb1, tf3)

f_sec(symb2, tf1)
f_sec(symb2, tf2)
f_sec(symb2, tf3)

f_sec(symb3, tf1)
f_sec(symb3, tf2)
f_sec(symb3, tf3)

f_sec(symb4, tf1)
f_sec(symb4, tf2)
f_sec(symb4, tf3)

f_sec(symb5, tf1)
f_sec(symb5, tf2)
f_sec(symb5, tf3)

f_sec(symb6, tf1)
f_sec(symb6, tf2)
f_sec(symb6, tf3)

f_sec(symb7, tf1)
f_sec(symb7, tf2)
f_sec(symb7, tf3)

f_sec(symb8, tf1)
f_sec(symb8, tf2)
f_sec(symb8, tf3)

f_sec(symb9, tf1)
f_sec(symb9, tf2)
f_sec(symb9, tf3)

f_sec(symb10, tf1)
f_sec(symb10, tf2)
f_sec(symb10, tf3)

f_sec(symb11, tf1)
f_sec(symb11, tf2)
f_sec(symb11, tf3)

f_sec(symb12, tf1)
f_sec(symb12, tf2)
f_sec(symb12, tf3)

f_sec(symb13, tf1)
f_sec(symb13, tf2)
f_sec(symb13, tf3)



scr_label = ""
symb_arr_size = array.size(symb_arr)

row_count = symb_arr_size/tfcount


any_fire_sqz_alert = false

any_adx_entry_alert = false

any_erg_entry_alert = false

any_summary_entry_alert = false


is_entry_alert(st,show_flag)=>
    show_flag and (st == STRAT_ENTER_LONG or st == STRAT_ENTER_SHORT or st == STRAT_EXIT_LONG or st == STRAT_EXIT_SHORT)



get_alert_info(st,show_flag,symb,tf,indicator_name)=>
    any_entry = false
    
    [dis_txt, dis_col] = decodeStratCode(st)
    
    if is_entry_alert(st , show_flag)
        any_entry := true
    
    symb_info = symb + sep + tf + sep + indicator_name + sep + dis_txt + '\n'

    [any_entry,symb_info,dis_col]


if symb_arr_size > 0 and barstate.islast
    var table tbl4 = table.new(position.middle_center, tfcount+1,row_count+1, frame_color=color(na), frame_width=1, border_width=2, border_color=color(na))

    table.cell(tbl4, 0, 0, 'Summary',     text_halign = text.align_center, bgcolor = color.gray, text_color = color.white, text_size = size.small)
    table.cell(tbl4, 1, 0, tf1,  text_halign = text.align_center, bgcolor = color.gray, text_color = color.white, text_size = size.small)
    table.cell(tbl4, 2, 0, tf2,  text_halign = text.align_center, bgcolor = color.gray, text_color = color.white, text_size = size.small)
    
    
    if tfcount >= 3
        table.cell(tbl4, 3, 0, tf3,  text_halign = text.align_center, bgcolor = color.gray, text_color = color.white, text_size = size.small)

    if tfcount >= 4
        table.cell(tbl4, 4, 0, tf4,  text_halign = text.align_center, bgcolor = color.gray, text_color = color.white, text_size = size.small)


    tab_i = 0
    tab_j = 0
    
    for i = 0 to symb_arr_size-1
        tab_i := floor(i/tfcount)
        tab_j := floor(i%tfcount)
        
        symb = array.get(symb_arr, i)
        tf = array.get(tf_arr, i)
        

        if tab_j == 0
            table.cell(tbl4, 0, tab_i + 1,symb ,text_halign = text.align_left,   bgcolor = color(na), text_color = color.white, text_size = size.small)



        fire_code = array.get(fire_sqz_arr, i)
        [fire_sqz_txt, fire_sqz_col] = decodeSqzColorCode(fire_code)

        sq_col_code = array.get(sqcolor_arr, i)
        [sq_col_txt, sq_col_obj] = decodeSqzColorCode(sq_col_code)
        
        
        fsqz_first_char = array.get(str.split(fire_sqz_txt,''),0)
        sqz_first_char = array.get(str.split(sq_col_txt,''),0)


        adx_code = array.get(adx_status_arr,i)
        [any_entry2,symb_info2,adx_col] = get_alert_info(adx_code,show_adx_alert,symb,tf,'ADX')
        if any_entry2
            scr_label := scr_label + symb_info2
            any_adx_entry_alert := any_entry2
        

        erg_code = array.get(erg_status_arr,i)
        [any_entry3,symb_info3,erg_col] = get_alert_info(erg_code,show_erg_alert,symb,tf,'ERG')
        if any_entry3
            scr_label := scr_label + symb_info3
            any_erg_entry_alert := any_entry3
        

        summ_trend_code = array.get(summ_status_arr,i)
        [any_entry4,symb_info4,summ_col] = get_alert_info(summ_trend_code,show_summ_alert,symb,tf,'SUMM')
        if any_entry4
            scr_label := scr_label + symb_info4
            any_summary_entry_alert := any_entry4
            
        
        sqz_dis_txt1 = ''
        if fire_code != NOSQZ and show_fire_alert
            any_fire_sqz_alert := true
            
            [dis_txt, dis_col] = decodeStratCode(summ_trend_code)

            symb_info = symb + sep + tf + sep + 'FIRE'+ sep + fire_sqz_txt + sep + dis_txt + '\n'
            scr_label := scr_label + symb_info
    
    
        sqz_dis_txt1 := fire_code != NOSQZ ? 'F'+fsqz_first_char: sqz_dis_txt1
        
        
        table.cell(tbl4, tab_j+1, tab_i + 1,sqz_dis_txt1 ,text_halign = text.align_center, bgcolor = summ_col, text_color = color.white, text_size = size.small)
        
        

// Send alert only if screener is not empty
if (scr_label != '' and (any_fire_sqz_alert or  any_summary_entry_alert or 
      any_adx_entry_alert or any_erg_entry_alert))
      
    final_msg = screener_sep + scr_label +screener_sep
    alert(final_msg, freq = alert.freq_once_per_bar_close)
    
