//@version=4
strategy(title="Sqz_ADX_Ergo Strategy", shorttitle="Sqz_ADX_Ergo", overlay=true, pyramiding=1,  
  calc_on_every_tick=true,initial_capital=2000000,default_qty_type=strategy.percent_of_equity, default_qty_value=100)




// OSc Code Consts

UP = 1
DOWN = 2
NEUTRAL = 0

YELLOW=1
RED=2
ORANGE=3
NOSQZ=0



//---
rad2degree=180/3.14159265359
lookback_period = 1
smoothing = 3


//Sqz Code variables
source = close

calc_sqz()=>
    length = 20
    ma = sma(source, length)
    devBB = stdev(source, length)
    devKC = sma(tr, length)
    
    
    //Bollinger 2x
    upBB = ma + devBB * 2
    lowBB = ma - devBB * 2
    
    //Keltner 2x
    upKCWide = ma + devKC * 2
    lowKCWide = ma - devKC * 2
    
    //Keltner 1.5x
    upKCNormal = ma + devKC * 1.5
    lowKCNormal = ma - devKC * 1.5
    
    //Keltner 1x
    upKCNarrow = ma + devKC
    lowKCNarrow = ma - devKC
    
    sqzOnWide = lowBB >= lowKCWide and upBB <= upKCWide  //WIDE SQUEEZE: ORANGE
    sqzOnNormal = lowBB >= lowKCNormal and upBB <= upKCNormal  //NORMAL SQUEEZE: RED
    sqzOnNarrow = lowBB >= lowKCNarrow and upBB <= upKCNarrow  //NARROW SQUEEZE: YELLOW
    sqzOffWide = lowBB < lowKCWide and upBB > upKCWide  //FIRED WIDE SQUEEZE
    sqzOffNormal = lowBB < lowKCNormal and upBB > upKCNormal  //FIRED NORMAL SQUEEZE
    sqzOffNarrow = lowBB < lowKCNarrow and upBB > upKCNarrow  //FIRED NARROW SQUEEZE
    noSqz = sqzOnWide == false and sqzOffWide == false  //NO SQUEEZE
    
    fire_code = sqzOffNarrow and sqzOnNarrow[1] ? YELLOW :
       sqzOffNormal and sqzOnNormal[1] ? RED :
       sqzOffWide and sqzOnWide[1] ? ORANGE : NOSQZ
    
    
    sqzcolornum = noSqz ? NOSQZ : sqzOnNarrow ? YELLOW : 
     sqzOnNormal ? RED : sqzOnWide ? ORANGE : NOSQZ

    
    [sqzcolornum,fire_code]
        

//------ End of Sqz Code--------

decodeSqzColorCode(st) => 
    col= st == YELLOW ? color.yellow : st == RED ? color.red : st == ORANGE ? color.orange : color.gray
    txt = st == YELLOW ? 'Yellow' : st == RED ? 'Red' : st == ORANGE ? 'Orange' : 'Nosqz'
    [txt, col]

decodeMovementCode(st) => 
    col = st == UP ? color.aqua : st == DOWN ? color.red : color.gray
    txt = st == UP ? 'Up' : st == DOWN ? 'Down' : 'Neutral'
    [txt, col]


angle(_src,osc_avg_tr) =>
    ang=rad2degree*atan((_src-nz(_src[lookback_period]))/(lookback_period*osc_avg_tr))
    
get_osc_movement_with_params(osc, osc_ft, osc_cut_off,osc_avg_atr,osc_MAX,osc_MIN) =>
    osc_fb = -osc_ft
    osc_slope = linreg(angle(osc,osc_avg_atr), smoothing, 0)
    trend = osc_slope > osc_ft or osc >= (osc_MAX - osc_cut_off) ? UP: osc_slope < osc_fb or osc <= (osc_MIN + osc_cut_off) ? DOWN : NEUTRAL
    trend


// ADX Code

STRAT_NEUTRAL = 0
STRAT_LONG = 1 
STRAT_SHORT = 2  
STRAT_ENTER_LONG =3
STRAT_ENTER_SHORT = 4 
STRAT_EXIT_LONG  =5
STRAT_EXIT_SHORT  = 6


decodeStratCode(adx_code)=>
    adx_col = adx_code == STRAT_EXIT_LONG ? color.new(color.yellow,transp= 0) : adx_code == STRAT_EXIT_SHORT ? color.new(color.blue,transp= 0) :  
       adx_code == STRAT_ENTER_LONG ? color.new(color.lime,transp= 0) : adx_code == STRAT_ENTER_SHORT ? color.new(color.red,transp=0) :  
       adx_code == STRAT_LONG ? color.new(color.aqua,transp= 60) : adx_code == STRAT_SHORT ? color.new(color.orange,transp= 60) : color.new(color.gray,transp= 60)
     
    
    adx_txt = adx_code == STRAT_EXIT_LONG ? 'ExUp' : adx_code == STRAT_EXIT_SHORT ? 'ExDn' :  
       adx_code == STRAT_ENTER_LONG ? 'EnUp' : adx_code == STRAT_ENTER_SHORT ? 'EnDn' :  
       adx_code == STRAT_LONG ? 'Up' : adx_code == STRAT_SHORT ? 'Dn' : 'Na'
     
    [adx_txt,adx_col]



RANGE_BACK_BARS = 100


calc_ADX() =>
    adx_len = 14
    adx_lensig = 14
    
    // Get ADX, PDI and MDI values
    [plus, minus, adx] = dmi(adx_len, adx_lensig)
    
    adx_MAX=highest(adx,RANGE_BACK_BARS)
    adx_MIN=lowest(adx,RANGE_BACK_BARS)
    
    
    adx_avg_tr =  adx_MAX - adx_MIN
    adx_cut_off= 0
    
    adx_filter_range = 2.55
    
    adx_ft = adx_filter_range
    adx_fb = -adx_filter_range
    
    
    adxentrylevel = 49
    adxlowerlevel = 9
    
    
    adx_trend = get_osc_movement_with_params(adx,adx_ft,adx_cut_off, adx_avg_tr,adx_MAX,adx_MIN)
    
    diPositive = plus > minus
    diNegative = not diPositive
    
    adxinside = (diPositive and adx >= minus and adx <= plus) or (diNegative and adx >= plus and adx <= minus)
    
    adxvalidtrend = adx_trend == UP or adx_trend == NEUTRAL 
    
    adxvalidtrendentry = (adx >= adxlowerlevel and adx <= adxentrylevel) or adxinside
     
    buyCond = diPositive and adxvalidtrend
    sellCond = diNegative and adxvalidtrend
    
    
    adxJustCrossed = cross(adx, plus) or cross(adx, minus)
    
    adxjustout = (adxinside[1] and not adxinside)
    adxjustin = (not adxinside[1] and adxinside)
    
    di_crossover = (diNegative[1] and diPositive) or (diNegative and diPositive[1]) 
    
    
    validlongentry = buyCond and adxvalidtrendentry
    validshortentry = sellCond and adxvalidtrendentry
    
    noTradeZone = not adxvalidtrend or di_crossover
    
    
    // get_active_position() =>
    active_position = false
    active_position := ((validlongentry or validshortentry) and not active_position[1] ? true : noTradeZone ? false : active_position[1])
    active_position

    //active_position = get_active_position()
    
    enterLong = validlongentry  and not active_position[1]
    enterShort =  validshortentry and not active_position[1]
    
    
    longpos = buyCond  and  active_position
    shortpos = sellCond and active_position
    
    
    exitLong = noTradeZone and longpos[1]
    exitShort = noTradeZone and shortpos[1]
    
    adx_status_code = exitLong ? STRAT_EXIT_LONG : exitShort ? STRAT_EXIT_SHORT :  
     enterLong ? STRAT_ENTER_LONG : enterShort ? STRAT_ENTER_SHORT :  
     longpos ? STRAT_LONG : shortpos ? STRAT_SHORT : STRAT_NEUTRAL
     
    adx_status_code



//----- SMI Ergo

calc_SMI_Erg()=>
    erg_longlen =14
    erg_shortlen = 8
    erg_siglen = 14
    erg_smoothing = 3
    
    erg1 = tsi(source, erg_shortlen, erg_longlen)
    
    erg = ema(erg1,erg_smoothing)
    
    sig = ema(erg1, erg_siglen)
    
    
    erg_MAX=highest(erg,RANGE_BACK_BARS)
    erg_MIN=lowest(erg,RANGE_BACK_BARS)
    
    erg_MID = (erg_MAX + erg_MIN)/2
    
    erg_avg_tr =  erg_MAX - erg_MIN
    erg_cut_off= 0
    
    erg_filter_range = 2
    
    erg_ft = erg_filter_range
    erg_fb = -erg_filter_range
    
    erg_trend = get_osc_movement_with_params(erg,erg_ft,erg_cut_off, erg_avg_tr,erg_MAX,erg_MIN)

    erg_validlong = erg_trend == UP
    erg_validshort =erg_trend == DOWN
    
    erg_diPositive = erg > sig
    erg_diNegative = not erg_diPositive
    
    
    erg_di_crossover = (erg_diNegative[1] and erg_diPositive) or (erg_diNegative and erg_diPositive[1]) 
    
    
    erg_buyCond = erg_diPositive and erg_trend != DOWN
    erg_sellCond = erg_diNegative and erg_trend != UP
    
    
    ergvalidtrend = erg_buyCond or erg_sellCond
    
    erg_validlongentry = erg_buyCond and erg_validlong 
    erg_validshortentry = erg_sellCond and erg_validshort
    
    erg_noTradeZone = not ergvalidtrend or erg_di_crossover 
    
    
    erg_active_position = false
    erg_active_position := ((erg_validlongentry or erg_validshortentry) and not erg_active_position[1] ? true : erg_noTradeZone ? false : erg_active_position[1])
    
    
    erg_enterLong = erg_validlongentry  and not erg_active_position[1] 
    erg_enterShort =  erg_validshortentry and not erg_active_position[1]
    
    
    erg_longpos = erg_buyCond  and  erg_active_position
    erg_shortpos = erg_sellCond and erg_active_position
    
    
    erg_exitLong = erg_noTradeZone and erg_longpos[1] 
    erg_exitShort = erg_noTradeZone and erg_shortpos[1]
    
    
    erg_status_code = erg_exitLong ? STRAT_EXIT_LONG : erg_exitShort ? STRAT_EXIT_SHORT :  
     erg_enterLong ? STRAT_ENTER_LONG : erg_enterShort ? STRAT_ENTER_SHORT :  
     erg_longpos ? STRAT_LONG : erg_shortpos ? STRAT_SHORT : STRAT_NEUTRAL
     
    erg_status_code


get_trend_num(trend_code) =>
    trend_code == UP ? 1 : trend_code == DOWN ? -1 : 0


get_all_status_codes() =>

    [sqzcolornum,fire_code] = calc_sqz()
    
    adx_status_code = calc_ADX()
    
    erg_status_code = calc_SMI_Erg()

    [fire_code,adx_status_code,erg_status_code]



get_status_code_trend_num(st) =>
    st == STRAT_ENTER_LONG or st == STRAT_LONG or st == STRAT_EXIT_SHORT ? 1 : st == STRAT_ENTER_SHORT or st == STRAT_SHORT or st == STRAT_EXIT_LONG ? -1 : 0


get_summary_trend_code(adx_code,erg_code) =>
    st_num = get_status_code_trend_num(adx_code) + 
      get_status_code_trend_num(erg_code)
     
    
    summ_trend_code = st_num >= 1 ? STRAT_LONG : st_num <= -1 ? STRAT_SHORT : STRAT_NEUTRAL
    
    
    any_long_entry = adx_code == STRAT_ENTER_LONG or erg_code == STRAT_ENTER_LONG
    
    any_short_entry = adx_code == STRAT_ENTER_SHORT or erg_code == STRAT_ENTER_SHORT

    summ_trend_code := (summ_trend_code == STRAT_LONG and any_long_entry and st_num == 2 )? STRAT_ENTER_LONG :   
      (summ_trend_code == STRAT_SHORT and any_short_entry and st_num == -2) ? STRAT_ENTER_SHORT :  summ_trend_code
    
    summ_trend_code
    
    

[fire_code,adx_code,erg_code] = get_all_status_codes() 


summ_trend_code = get_summary_trend_code(adx_code,erg_code)
[summ_txt, summ_col] = decodeStratCode(summ_trend_code)
        

curr_active_pos = false
curr_active_pos := curr_active_pos[1]


buyCond = summ_trend_code == STRAT_ENTER_LONG or summ_trend_code == STRAT_LONG
sellCond = summ_trend_code == STRAT_ENTER_SHORT or summ_trend_code == STRAT_SHORT


validtrend = buyCond or sellCond

validlongentry = summ_trend_code == STRAT_ENTER_LONG  
validshortentry = summ_trend_code == STRAT_ENTER_SHORT


enterLong = validlongentry  and not curr_active_pos
enterShort =  validshortentry and not curr_active_pos


// enterLong = buyCond  and not curr_active_pos
// enterShort =  sellCond and not curr_active_pos


curr_active_pos := (enterLong or enterShort) ? true :  curr_active_pos


longpos = buyCond  and  curr_active_pos 
shortpos = sellCond and  curr_active_pos

di_change = (longpos[1] and not buyCond) or (shortpos[1] and not sellCond) 
noTrade =  di_change or not validtrend 

exitLong = noTrade and longpos[1] and curr_active_pos[1]
exitShort = noTrade and shortpos[1] and curr_active_pos[1]


curr_active_pos := (exitLong or exitShort) ? false : curr_active_pos


final_summary_status_code = exitLong ? STRAT_EXIT_LONG : exitShort ? STRAT_EXIT_SHORT :  
     enterLong ? STRAT_ENTER_LONG : enterShort ? STRAT_ENTER_SHORT :  
     longpos ? STRAT_LONG : shortpos ? STRAT_SHORT : STRAT_NEUTRAL


[fin_sum__txt, fin_summ_col] = decodeStratCode(final_summary_status_code)


[fire_sqz_txt, fcolor] = decodeSqzColorCode(fire_code)
firedown = fire_code != NOSQZ and shortpos
fireup =  fire_code != NOSQZ and longpos

fireneutral = fire_code != NOSQZ and not firedown  and not fireup


//FIRED SIGNALS
plotshape(firedown, title='Fired Short', style=shape.triangledown, location=location.abovebar, color=color.white, size=size.small)
plotshape(firedown, title='Fired Short circle', style=shape.circle, location=location.abovebar, color=fcolor, size=size.tiny)

plotshape(fireup, title='Fired Long', style=shape.triangleup, location=location.belowbar, color=color.white, size=size.small)
plotshape(fireup, title='Fired Long circle', style=shape.circle, location=location.belowbar, color=fcolor, size=size.tiny)

plotshape(fireneutral, title='Fired Neutral', style=shape.square, location=location.belowbar, color=color.gray, size=size.small)
plotshape(fireneutral, title='Fired Neutral circle', style=shape.circle, location=location.belowbar, color=fcolor, size=size.tiny)



bgcolor(color.new(fin_summ_col,transp=80))



// ---------- EMAs --------------

out8 = ema(source, 8)
plot(out8, title="EMA - 1", color=color.new(color.silver, transp = 0), linewidth=1)

out21 = ema(source, 21)
plot(out21, title="EMA - 2", color=color.new(color.aqua, transp = 0), linewidth=1)

out34 = ema(source, 34)
plot(out34, title="EMA - 3", color=color.new(color.blue, transp = 0), linewidth=1)

out55 = ema(source, 55)
plot(out55, title="EMA - 4", color=color.new(color.lime, transp = 0), linewidth=1)

out89 = ema(source, 89)
plot(out89, title="EMA - 5", color=color.new(color.yellow, transp = 0), linewidth=1)

out144 = ema(source, 144)
plot(out144, title="EMA - 6", color=color.new(color.red, transp = 0), linewidth=1)

//out233 = ema(source, 233)
//plot(out233, title="EMA - 7", color=color.yellow, linewidth=1, transp=0)



//----- Strategy

start     = timestamp(2021, 10, 1, 00, 00)            // backtest start  window
finish    = timestamp(2022, 12, 31, 00, 00)              // backtest finish window
window()  => time >= start and time <= finish ? true : false           // create function "within window of time"


strategy.entry("long", strategy.long, when = window() and enterLong)
strategy.close("long", when = window() and exitLong)


strategy.entry("short", strategy.short, when = window() and enterShort)
strategy.close("short", when = window() and exitShort)


