[settings]
reload_interval = 3
buffer_seconds = 5
debug = true
ignore_lastseen = false
no_trade = false
rebuild_master_scrip = false
candidate_files = ['candidates.txt', 'candidates_comm.txt', 'candidates_tv.txt', 'candidates_cryp.txt']

[tv_symbol_map]
USOIL = "CRUDEOIL"
CNXFINANCE = "FINNIFTY"
NIFTY_MID_SELECT = "MIDCPNIFTY"

[coordinates]
x1 = 1004
y1 = 109
x2 = 1424
y2 = 462
signal_col_x = 157
