//@version=6
indicator(title = 'Strategy', shorttitle = 'StrategyH', overlay = true)


source = close
volsrc = volume

var india_tz = 'Asia/Kolkata'
var use_vol_kst = input(true, 'Use Volume Indicator')

var atr_length = 5
var atr_mult = 1
atr = ta.atr(atr_length)

var len1 = 8
var len2 = 21
var len3 = 55
var len4 = 233
var rsilen = 8
var rsiMAlen = 13
var sig_rsiMAlen = 13 
var hl = 66.7
var hl_1 = 59.5
var hl_2 = 53.9
var ml = 50
var ll_2 = 46
var ll_1 = 41.2
var ll = 33.3

var lineup_check = input.int(2, title = 'Lineup Check', options = [1, 2, 3, 4])
var ma_filter = input.int(2, title = 'MA Filter', options = [1, 2, 3, 4])
var strict_confirm_trade_check = input.int(0, title = 'Strict confirm trade check', options = [0, 1, 2, 3])

var last_n_days = input.float(60, 'Days')
var show_only_window = input(true, title = 'Show trades in window')
var MILLISECONDS_IN_DAY = 24 * 60 * 60 * 1000
 
var start = show_only_window ? math.max(int(timenow - MILLISECONDS_IN_DAY * last_n_days),time[0]) : time[0]

window() => // create function "within window of time"
    time >= start


var long_signal_flag = input(true, title = 'Long Signal')
var short_signal_flag = input(true, title = 'Short Signal')


// ---------- EMAs --------------

out1 = ta.rma(source, len1)
out2 = ta.rma(source, len2)
out3 = ta.rma(source, len3)
out4 = ta.rma(source, len4)



// OSc Code Consts

var UP = 1
var DOWN = 2
var NEUTRAL = 0


// OSc Constants
var rad2degree = 180 / 3.14159265359
var lookback_period = 1
var smoothing = 3

var RANGE_BACK_BARS = 20
var osc_filter_range = 5.2


angle(_src, osc_avg_tr) =>
    ang = rad2degree * math.atan((_src - nz(_src[lookback_period])) / (lookback_period * osc_avg_tr))
    ang


get_osc_trend_params(osc, osc_filter) =>
    osc_max = ta.highest(osc, RANGE_BACK_BARS)
    osc_min = ta.lowest(osc, RANGE_BACK_BARS)

    osc_avg_tr = osc_max - osc_min

    osc_ft = osc_filter
    osc_fb = -osc_ft

    osc_slope = ta.linreg(angle(osc, osc_avg_tr), smoothing, 0)
    trend = osc_slope >= osc_ft or osc >= osc_max ? UP : osc_slope <= osc_fb or osc <= osc_min ? DOWN : NEUTRAL
    trend


get_osc_trend(osc) =>
    get_osc_trend_params(osc, osc_filter_range)


// Code Constants

var STRAT_NEUTRAL = 0
var STRAT_LONG = 1
var STRAT_SHORT = 2
var STRAT_ENTER_LONG = 3
var STRAT_ENTER_SHORT = 4
var STRAT_EXIT_LONG = 5
var STRAT_EXIT_SHORT = 6

var exitlong_col = color.new(color.yellow, transp = 70)
var exitshort_col = color.new(color.blue, transp = 70)
var enterlong_col = color.new(color.lime, transp = 70)
var entershort_col = color.new(color.red, transp = 70)
var longpos_col = color.new(color.aqua, transp = 80)
var shortpos_col = color.new(color.orange, transp = 80)
var neutral_col = color(na) 


calc_generic_osc(fastma, sigma, center_level=0, short_entry_flag=true) => 

    osc_trend = get_osc_trend(fastma)

    osc_validlong = osc_trend == UP
    osc_validshort = osc_trend == DOWN

    osc_diPositive = fastma > sigma
    osc_diNegative = not osc_diPositive


    osc_di_crossover = osc_diNegative[1] and osc_diPositive or osc_diNegative and osc_diPositive[1]


    osc_buyCond = osc_diPositive and fastma >= center_level
    osc_sellCond = osc_diNegative and fastma < center_level


    osc_validtrend = osc_buyCond or osc_sellCond

    osc_validlongentry = osc_buyCond and osc_validlong 
    osc_validshortentry = osc_sellCond and osc_validshort and short_entry_flag

    osc_noTradeZone = not osc_validtrend or osc_di_crossover


    osc_active_position = false
    osc_active_position := (osc_validlongentry or osc_validshortentry) and not osc_active_position[1] ? true : osc_noTradeZone ? false : osc_active_position[1]


    osc_enterLong = osc_validlongentry and not osc_active_position[1]
    osc_enterShort = osc_validshortentry and not osc_active_position[1]


    osc_longpos = osc_buyCond and osc_active_position
    osc_shortpos = osc_sellCond and osc_active_position


    osc_exitLong = osc_noTradeZone and osc_longpos[1]
    osc_exitShort = osc_noTradeZone and osc_shortpos[1]


    osc_status_code = osc_exitLong ? STRAT_EXIT_LONG : osc_exitShort ? STRAT_EXIT_SHORT : osc_enterLong ? STRAT_ENTER_LONG : osc_enterShort ? STRAT_ENTER_SHORT : osc_longpos ? STRAT_LONG : osc_shortpos ? STRAT_SHORT : STRAT_NEUTRAL

    osc_status_code



// Calc EMAs Trend

out1_trend = get_osc_trend(out1)
out2_trend = get_osc_trend(out2)


decodeStratCode(adx_code) =>
    adx_col = neutral_col
    adx_col := adx_code == STRAT_EXIT_LONG ? exitlong_col : adx_code == STRAT_EXIT_SHORT ? exitshort_col : adx_code == STRAT_ENTER_LONG ? enterlong_col : adx_code == STRAT_ENTER_SHORT ? entershort_col : adx_code == STRAT_LONG ? longpos_col : adx_code == STRAT_SHORT ? shortpos_col : neutral_col
    adx_txt = adx_code == STRAT_EXIT_LONG ? 'ExUp' : adx_code == STRAT_EXIT_SHORT ? 'ExDn' : adx_code == STRAT_ENTER_LONG ? 'EnUp' : adx_code == STRAT_ENTER_SHORT ? 'EnDn' : adx_code == STRAT_LONG ? 'Up' : adx_code == STRAT_SHORT ? 'Dn' : 'Na'
    [adx_txt, adx_col]


calc_RSI() =>

    rsi = ta.rsi(source, rsilen)
    rsiMA = ta.rma(rsi, rsiMAlen)
    sig_rsiMA = ta.rma(rsiMA, sig_rsiMAlen)

    status_code = calc_generic_osc(rsiMA, sig_rsiMA, center_level=ml)
    status_code


checkEMA(isLong, isPriceEMA) =>

    valid = false

    extra_ma_long_filter = switch ma_filter
        4 => source >= out4
        3 => source >= out3
        2 => source >= out2
        1 => source >= out1

    extra_ma_short_filter = switch ma_filter
        4 => source <= out4
        3 => source <= out3
        2 => source <= out2
        1 => source <= out1


    extra_long_check = out1_trend == UP and extra_ma_long_filter
    extra_short_check = out1_trend == DOWN and extra_ma_short_filter

    if lineup_check >= 2
        extra_long_check := extra_long_check and out2_trend == UP and out1 >= out2
        extra_short_check := extra_short_check and out2_trend == DOWN and out1 <= out2
        extra_short_check

    if lineup_check >= 3
        strict_long_ma_check = source >= out3 and out1 >= out2 and out2 >= out3
        strict_short_ma_check = source <= out3 and out1 <= out2 and out2 <= out3

        if lineup_check == 4
            strict_long_ma_check := source >= out4 and out3 >= out4 and strict_long_ma_check
            strict_short_ma_check := source <= out4 and out3 <= out4 and strict_short_ma_check
            strict_short_ma_check

        extra_long_check := extra_long_check and strict_long_ma_check
        extra_short_check := extra_short_check and strict_short_ma_check
        extra_short_check


    if isLong
        if extra_long_check or isPriceEMA and source >= out2
            valid := true
            valid
    else if extra_short_check or isPriceEMA and source <= out2
        valid := true
        valid

    
    valid


get_trend_num(trend_code) =>
    trend_code == UP ? 1 : trend_code == DOWN ? -1 : 0



// KST code 
var roclen1 = 8 
var roclen2 = 13 
var roclen3 = 21 
var roclen4 = 34 
var smalen1 = 8 
var smalen2 = 8 
var smalen3 = 8
var smalen4 = 13 
var siglen = 13

smaroc(cust_source,roclen, smalen) => ta.rma(ta.roc(cust_source, roclen), smalen)
calc_custom_kst(cust_source) => smaroc(cust_source,roclen1, smalen1) + 2 * smaroc(cust_source,roclen2, smalen2) + 3 * smaroc(cust_source,roclen3, smalen3) + 4 * smaroc(cust_source,roclen4, smalen4)



calc_vol_KST() =>

    kst = calc_custom_kst(volsrc)
    sig = ta.rma(kst, siglen)

    kst_status_code = calc_generic_osc(kst, sig, short_entry_flag=false)
    kst_status_code




calc_KST() =>
    kst = calc_custom_kst(source)
    sig = ta.rma(kst, siglen)

    kst_status_code = calc_generic_osc(kst, sig)
    kst_status_code

 

get_all_status_codes() =>

    rsi_code = calc_RSI()
    kst_code = calc_KST()
    vol_kst_code = calc_vol_KST()
    [rsi_code, kst_code, vol_kst_code]



get_status_code_trend_num(st) =>
    st == STRAT_ENTER_LONG or st == STRAT_LONG or st == STRAT_EXIT_SHORT ? 1 : st == STRAT_ENTER_SHORT or st == STRAT_SHORT  or st == STRAT_EXIT_LONG? -1 : 0


get_summary_trend_code(rsi_code, kst_code) =>

    summ_trend_code = STRAT_NEUTRAL

    rsi_num = get_status_code_trend_num(rsi_code)
    kst_num = get_status_code_trend_num(kst_code)

    st_num = rsi_num + kst_num
    summ_trend_code := st_num == 2? STRAT_ENTER_LONG : st_num == 1 ?  STRAT_LONG : st_num  == -2 ?  STRAT_ENTER_SHORT : st_num == -1 ? STRAT_SHORT : STRAT_NEUTRAL
        
    summ_trend_code



[rsi_code, kst_code,vol_kst_code] = get_all_status_codes()


summ_trend_code = get_summary_trend_code(rsi_code, kst_code)
[summ_txt, summ_col] = decodeStratCode(summ_trend_code)


curr_active_pos = false
longpos = false
shortpos = false

curr_active_pos := curr_active_pos[1]




buyCond = (summ_trend_code == STRAT_ENTER_LONG or summ_trend_code == STRAT_LONG) //and checkEMA(true, true)

sellCond = (summ_trend_code == STRAT_ENTER_SHORT or summ_trend_code == STRAT_SHORT) //and checkEMA(false, true)



neutralCond = not buyCond and not sellCond


validlongentry = buyCond and summ_trend_code == STRAT_ENTER_LONG and checkEMA(true, false) and window()
validshortentry = sellCond and summ_trend_code == STRAT_ENTER_SHORT and checkEMA(false, false) and window()


vol_kst_active = vol_kst_code == STRAT_ENTER_LONG or vol_kst_code == STRAT_LONG
check_vol_kst = not use_vol_kst or vol_kst_active

enterLong = validlongentry and not curr_active_pos and long_signal_flag and check_vol_kst
enterShort = validshortentry and not curr_active_pos and short_signal_flag and check_vol_kst


curr_active_pos := enterLong or enterShort ? true : curr_active_pos

longpos := curr_active_pos and (buyCond or longpos[1] and neutralCond)
shortpos := curr_active_pos and (sellCond or shortpos[1] and neutralCond)

di_change = longpos[1] and sellCond or shortpos[1] and buyCond

noTrade = di_change

exitLong = noTrade and longpos[1] and curr_active_pos[1]
exitShort = noTrade and shortpos[1] and curr_active_pos[1]


curr_active_pos := exitLong or exitShort ? false : curr_active_pos

final_summary_status_code = exitLong ? STRAT_EXIT_LONG : exitShort ? STRAT_EXIT_SHORT : enterLong ? STRAT_ENTER_LONG : enterShort ? STRAT_ENTER_SHORT : longpos ? STRAT_LONG : shortpos ? STRAT_SHORT : STRAT_NEUTRAL


//----- Strategy

calc_trigger_entry(f_st) =>

    f_enterLong = f_st == STRAT_ENTER_LONG
    f_enterShort = f_st == STRAT_ENTER_SHORT

    f_exitLong = f_st == STRAT_EXIT_LONG
    f_exitShort = f_st == STRAT_EXIT_SHORT


    curr_long_entry_val = float(na)
    curr_short_entry_val = float(na)

    curr_long_entry_val := curr_long_entry_val[1]
    curr_short_entry_val := curr_short_entry_val[1]

    if f_enterLong[1]
        high_3 = math.max(high[1], high[2], high)
        long_entry_val = high_3
        curr_long_entry_val := long_entry_val + atr * atr_mult
        curr_long_entry_val

    if f_enterShort[1]
        low_3 = math.min(low[1], low[2], low)
        short_entry_val = low_3
        curr_short_entry_val := short_entry_val - atr * atr_mult
        curr_short_entry_val


    if f_exitLong
        curr_long_entry_val := float(na)
        curr_long_entry_val

    if f_exitShort
        curr_short_entry_val := float(na)
        curr_short_entry_val


    trigg_active_pos = false
    trigg_longpos = false
    trigg_shortpos = false
    trigg_active_pos := trigg_active_pos[1]


    first_trigg_enterLong = not trigg_active_pos and not na(curr_long_entry_val) and source > curr_long_entry_val and barstate.isconfirmed
    first_trigg_enterShort = not trigg_active_pos and not na(curr_short_entry_val) and source < curr_short_entry_val and barstate.isconfirmed


    first_long_entry_val = float(na)
    first_short_entry_val = float(na)

    first_long_entry_val := first_long_entry_val[1]
    first_short_entry_val := first_short_entry_val[1]

    first_long_entry_val := first_trigg_enterLong and na(first_long_entry_val) ? high : first_long_entry_val
    first_short_entry_val := first_trigg_enterShort and na(first_short_entry_val) ? low : first_short_entry_val


    if f_exitLong
        first_long_entry_val := float(na)
        first_long_entry_val

    if f_exitShort
        first_short_entry_val := float(na)
        first_short_entry_val


    second_trigg_enterLong = not trigg_active_pos and not na(first_long_entry_val) and source > first_long_entry_val and barstate.isconfirmed
    second_trigg_enterShort = not trigg_active_pos and not na(first_short_entry_val) and source < first_short_entry_val and barstate.isconfirmed

    second_long_entry_val = float(na)
    second_short_entry_val = float(na)

    second_long_entry_val := second_long_entry_val[1]
    second_short_entry_val := second_short_entry_val[1]

    second_long_entry_val := second_trigg_enterLong and na(second_long_entry_val) ? high : second_long_entry_val
    second_short_entry_val := second_trigg_enterShort and na(second_short_entry_val) ? low : second_short_entry_val


    if f_exitLong
        second_long_entry_val := float(na)
        second_long_entry_val

    if f_exitShort
        second_short_entry_val := float(na)
        second_short_entry_val


    third_trigg_enterLong = not trigg_active_pos and not na(second_long_entry_val) and source > second_long_entry_val and barstate.isconfirmed
    third_trigg_enterShort = not trigg_active_pos and not na(second_short_entry_val) and source < second_short_entry_val and barstate.isconfirmed

    trigg_enterLong = strict_confirm_trade_check == 1 ? first_trigg_enterLong : strict_confirm_trade_check == 2 ? second_trigg_enterLong : third_trigg_enterLong
    trigg_enterShort = strict_confirm_trade_check == 1 ? first_trigg_enterShort : strict_confirm_trade_check == 2 ? second_trigg_enterShort : third_trigg_enterShort


    trigg_active_pos := trigg_enterLong or trigg_enterShort ? true : trigg_active_pos

    trigg_longpos := trigg_active_pos and (trigg_enterLong or trigg_longpos[1])
    trigg_shortpos := trigg_active_pos and (trigg_enterShort or trigg_shortpos[1])


    trigg_exitLong = f_exitLong and trigg_active_pos
    trigg_exitShort = f_exitShort and trigg_active_pos


    trigg_active_pos := trigg_exitLong or trigg_exitShort ? false : trigg_active_pos


    trigg_status_code = trigg_exitLong ? STRAT_EXIT_LONG : trigg_exitShort ? STRAT_EXIT_SHORT : trigg_enterLong ? STRAT_ENTER_LONG : trigg_enterShort ? STRAT_ENTER_SHORT : trigg_longpos ? STRAT_LONG : trigg_shortpos ? STRAT_SHORT : STRAT_NEUTRAL

    trigg_status_code



trigg_status_code = calc_trigger_entry(final_summary_status_code)
fin_status_code = strict_confirm_trade_check != 0 ? trigg_status_code : final_summary_status_code

[fin_txt, fin_status_col] = decodeStratCode(fin_status_code)

bgcolor(fin_status_col)


final_long_pos = fin_status_code == STRAT_LONG or fin_status_code == STRAT_ENTER_LONG or fin_status_code == STRAT_EXIT_LONG
final_short_pos = fin_status_code == STRAT_SHORT or fin_status_code == STRAT_ENTER_SHORT or fin_status_code == STRAT_EXIT_SHORT

final_open_pos = final_long_pos or final_short_pos



plot(out1, title = 'RMA - 1', color = color.new(color.silver, transp = 0), linewidth = 2)
plot(out2, title = 'RMA - 2', color = color.new(color.aqua, transp = 0), linewidth = 2)
//plot(out3, title = 'RMA - 3', color = color.new(color.yellow, transp = 0), linewidth = 2)
//plot(out4, title = 'RMA - 4', color = color.new(color.red, transp = 0), linewidth = 2)



final_enterLong = fin_status_code == STRAT_ENTER_LONG
final_enterShort = fin_status_code == STRAT_ENTER_SHORT

final_exitLong = fin_status_code == STRAT_EXIT_LONG
final_exitShort = fin_status_code == STRAT_EXIT_SHORT


var sep = ' : '


raise_alert(ord_type) =>
    alert(ord_type + sep + str.tostring(source), freq = alert.freq_once_per_bar_close)



var trades= 0
var win_trades = 0
var total_maxp = 0.0

var maxp = 0.0
var entry_val = 0.0
var curr_prof = 0.0


is_neutral = fin_status_code == STRAT_NEUTRAL

if barstate.isconfirmed and not is_neutral
    trades := nz(trades[1])
    win_trades := nz(win_trades[1])
    total_maxp := nz(total_maxp[1])
    
    sig_long = fin_status_code == STRAT_ENTER_LONG or fin_status_code == STRAT_LONG or fin_status_code == STRAT_EXIT_LONG
    entry_val := final_enterLong or final_enterShort ? source : nz(entry_val[1])

    bv = sig_long ? entry_val : source
    sv = sig_long ? source : entry_val

    curr_prof := (sv - bv) * 100 / bv
    maxp := nz(maxp[1]) > curr_prof ? nz(maxp[1]) : curr_prof


    if final_exitLong or final_exitShort
        trades := trades + 1
        total_maxp := total_maxp + maxp

        if curr_prof >= 0
            win_trades := win_trades +1


        maxp := 0.0
        entry_val := 0.0
        curr_prof := 0.0



if final_enterLong
    raise_alert('U')

if final_exitLong
    raise_alert('XU')

if final_enterShort
    raise_alert('D')

if final_exitShort
    raise_alert('XD')


convert_time_to_str (time_val)=>
    str.tostring(dayofmonth(time_val, india_tz)) + '/' + str.tostring(month(time_val, india_tz)) + '_' + str.tostring(hour(time_val, india_tz)) + ':' + str.tostring(minute(time_val, india_tz))


if barstate.islastconfirmedhistory
    if not is_neutral and not (final_exitLong or final_exitShort)
        trades := trades + 1
        total_maxp := total_maxp + maxp

        if curr_prof >= 0.0
            win_trades := win_trades +1


    // label.new(bar_index, high, text= str.tostring(math.round(maxrunup,2)) + " | "+  str.tostring(total_trades) + " | "+ str.tostring(max_run_avg))
    var table tbl1 = table.new(position.top_right, 2, 6, frame_color = na, frame_width = 1, border_width = 2, border_color = na)
    
    table.cell(tbl1, 0, 0, 'From: '+convert_time_to_str(start), text_halign = text.align_center, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 0, 1, 'Trades', text_halign = text.align_center, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 0, 2, 'MaxPct', text_halign = text.align_center, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 0, 3, 'MaxPCTAvg', text_halign = text.align_center, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 0, 4, 'WinRate', text_halign = text.align_center, bgcolor = na, text_color = color.white, text_size = size.small)

    table.cell(tbl1, 1, 0, 'To: '+convert_time_to_str(time), text_halign = text.align_left, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 1, 1, str.tostring(trades), text_halign = text.align_left, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 1, 2, str.tostring(math.round(total_maxp, 2)), text_halign = text.align_left, bgcolor = na, text_color = color.white, text_size = size.small)
    
    mxpavg = trades == 0 ? 0 : total_maxp/trades
    winrt = trades == 0? 0 : float(win_trades)/trades

    table.cell(tbl1, 1, 3, str.tostring(math.round(mxpavg, 2)), text_halign = text.align_left, bgcolor = na, text_color = color.white, text_size = size.small)
    table.cell(tbl1, 1, 4, str.tostring(math.round(winrt, 2)), text_halign = text.align_left, bgcolor = na, text_color = color.white, text_size = size.small)
