# Global Config
place_order_mode= "SUPER"  # 'SUPER' 'FOREVER' 'ALERT' 
#def_expiry_date  = "2026-05-26"
def_trade_amount = 50000
def_quantity     = 1
def_order_mode   = 'NA'

# ─────────────────────────────────────────────
# Trade Level Percentages
# ─────────────────────────────────────────────
entry_price_perc = 0.13
limit_price_perc = 0.5
target_perc      = 4
stop_loss_perc   = 0.7
stop_trail_perc  = 0.35


# ─────────────────────────────────────────────
# NSE Configs
# ─────────────────────────────────────────────
[nse.stocks.config]
    order_mode   = "EQ" # EQ /OPT/ FUT
    trade_amount = 50000
    #expiry_date = "2026-05-26"

[nse.indices.config]
    order_mode = "NA"  # FUT/ OPT / NA

[nse.indices.symbols.NIFTY]
    #expiry_date = "2026-05-12"

[nse.indices.symbols.MIDCPNIFTY]
[nse.indices.symbols.BANKNIFTY]
[nse.indices.symbols.FINNIFTY]



# ─────────────────────────────────────────────
# MCX Configs
# ─────────────────────────────────────────────
[mcx.comm.config]
    order_mode = "NA" # FUT NA

[mcx.comm.symbols.CRUDEOIL]
    symbol      = "CRUDEOILM"
    quantity    = 5
    #expiry_date = "2026-05-14"

[mcx.comm.symbols.NATURALGAS]
    symbol      = "NATGASMINI"
    quantity    = 5
    # expiry_date = "2026-05-22"
    #put_strike  = 280

[mcx.comm.symbols.GOLD]
    symbol      = "GOLDM"
    quantity    = 1
    # expiry_date = "2026-05-29"
    #strike      = 140000

[mcx.comm.symbols.SILVER]
    # order_mode = "NA"
    symbol      = "SILVERM"
    quantity    = 1
    #strike      = 260000
    #call_strike = 270000
    #expiry_date = "2026-05-26"