max_log_size = 50 #KB

[scripts.app]
module = "web_scripts.nse_vol_tracker.app"
args = []

[scripts.tv_update]
module = "tradeview.tv_update"
args = []

[scripts.tv_scanner]
module = "tradeview.tv_scanner"
args = []