max_log_size = 50 #KB

[scripts.vol_app]
module = "apps.nse_vol_tracker.vol_app"
args = []

[scripts.tv_update]
module = "apps.tradeview.tv_update"
args = ['--remote-flag']

[scripts.tv_scanner]
module = "apps.tradeview.tv_scanner"
args = []

[scripts.trade_app]
module = "apps.trade_client.trade_app"
args = []